### ISSUE TITLE
Domains in excludeDomains are still included in results

### ISSUE THREAD

**Issue by siquick** [exa-labs/exa-js#23]
Results include domains that are in the excludeDomain array - present in Playground and in the JS library.

Example below

[Playground](https://dashboard.exa.ai/playground/search?q=Mr%20G%20-%20Positive%20Connection%20EP%20(NDATL%20Muzik%20US)%20vinyl&filters=%7B%22type%22%3A%22keyword%22%2C%22numResults%22%3A10%2C%22excludeDomains%22%3A%5B%22djmag.com%22%2C%22ebay.com.au%22%2C%22wordandsound.net%22%2C%221001tracklists.com%22%2C%22themusicessentials.com%22%2C%22allmusic.com%22%2C%22xlr8r.com%22%2C%22juno.co.uk%22%2C%22walmart.ca%22%2C%22instagram.com%22%2C%22ebay.co.uk%22%2C%22barnesandnoble.com%22%2C%22merchbar.com%22%2C%22ebay.com%22%2C%22discogs.com%22%2C%22walmart.com%22%2C%22discogs.com%22%2C%22soundcloud.com%22%2C%22rateyourmusic.com%22%2C%22ra.co%22%2C%22amazon.com.au%22%2C%22amazon.com%22%2C%22amazon.co.uk%22%2C%22amazon.in%22%2C%22amazon.de%22%2C%22last.fm%22%2C%22youtube.com%22%2C%22blogspot.com%22%2C%22reddit.com%22%2C%22pinterest.com%22%2C%22pinterest.co.uk%22%2C%22musicbrainz.org%22%2C%22beatport.com%22%2C%22traxsource.com%22%2C%22allmusic.com%22%2C%22pitchfork.com%22%2C%22spotify.com%22%2C%22apple.com%22%2C%22factmag.com%22%2C%22junodownload.com%22%2C%22medium.com%22%2C%22newslocker.com%22%2C%221001tracklists.com%22%2C%22shazam.com%22%2C%22hyponik.com%22%2C%22stampthewax.com%22%2C%22residentadvisor.net%22%2C%22facebook.com%22%2C%22walmart.com%22%2C%22target.com%22%2C%22ebay.com%22%2C%22merchbar.com%22%2C%22vinyl.com%22%2C%22soundshelter.net%22%5D%7D)

JS library:

```
import Exa from "exa-js"

const exa = new Exa(EXA_API_KEY);

const result = await exa.search(
  "Mr G - Positive Connection EP (NDATL Muzik US) vinyl",
  {
    type: "keyword",
    numResults: 10,
    excludeDomains: ["djmag.com", "ebay.com.au", "wordandsound.net", "1001tracklists.com", "themusicessentials.com", "allmusic.com", "xlr8r.com", "juno.co.uk", "walmart.ca", "instagram.com", "ebay.co.uk", "barnesandnoble.com", "merchbar.com", "ebay.com", "discogs.com", "walmart.com", "soundcloud.com", "rateyourmusic.com", "ra.co", "amazon.com.au", "amazon.com", "amazon.co.uk", "amazon.in", "amazon.de", "last.fm", "youtube.com", "blogspot.com", "reddit.com", "pinterest.com", "pinterest.co.uk", "musicbrainz.org", "beatport.com", "traxsource.com", "allmusic.com", "pitchfork.com", "spotify.com", "apple.com", "factmag.com", "junodownload.com", "medium.com", "newslocker.com", "1001tracklists.com", "shazam.com", "hyponik.com", "stampthewax.com", "residentadvisor.net", "facebook.com", "walmart.com", "target.com", "ebay.com", "merchbar.com", "vinyl.com","soundshelter.net"]
  }
)
```

Results (valid results excluded for brevity):

```
{
  "results": [
    ...
    {
      "title": "Mr. G – Positive Connection EP",
      "url": "https://www.youtube.com/watch?v=e-OQ3ymG2xQ",
      "author": null,
      "id": "https://www.youtube.com/watch?v=e-OQ3ymG2xQ"
    },
    ...
    {
      "title": "Ndatl Muzik Vinyl",
      "url": "https://www.soundshelter.net/label/ndatl-muzik",
      "author": null,
      "id": "https://www.soundshelter.net/label/ndatl-muzik"
    },
  ],
  "requestId": "abc123"
}
```

**Comment by Feel-ix-343** [comment]
Thank you for reporting!

Exclude + include domains for keyword search is really funky right now, and I'd recommend retrying with fewer domains for now. 

We can work on improving this, but the future is really in neural search! We are adding more support for phrase + domain + keyword filters in this, so I really recommend trying that out for your usecase. 

Hope this helps.
